# Gradient Workflow Tutorial
#
# This is the YAML file used to run the Gradient modeling Workflow for the sample project based on StyleGAN2 at
# https://docs.paperspace.com.
#
#
# Last updated: Dec 07 2021
#
# Trigger Workflow to run on any update (commit) to the repository when linked to a Gradient project
# (uncomment to activate)

on:
 github:
   branches:
     only: main

jobs:

  # 1. Clone StyleGAN repo into managed storage provider dataset

  cloneStyleGAN2Repo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/NEBULA3PR0JECT/StyleGAN2-test.git

  # 2. Get pretrained cat model

  # The model .pkl is large so is not in the main StyleGAN2 repo
  # We copy the .pkl in this step, then refer to the copy via getPretrainedModelCats.outputs.pretrainedNetwork
  # below to avoid copying it again in the next steps

  printEnv1:
    resources:
      instance-type: C4
    needs:
      - cloneStyleGAN2Repo
    inputs:
      repo: cloneStyleGAN2Repo.outputs.repo
    uses: script@v1
    with:
      script: |-
        cp -R /inputs/repo /stylegan2
        cd /stylegan2
        python run_test.py
      image: python:3

  printEnv2:
    resources:
      instance-type: C4
    needs:
      - printEnv1
    inputs:
      repo: cloneStyleGAN2Repo.outputs.repo
    uses: script@v1
    with:
      script: |-
        cp -R /inputs/repo /stylegan2
        cd /stylegan2
        python run_test.py
      image: python:3
